title: My projects
email: luc@tech-hunters.com
description: >-
  This is about all my projects, anouncements, roadmaps, etc...
baseurl: ''
url: ''
github_username: luc-github
theme: minima
plugins:
  - jekyll-feed
